{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "templatepg.fullname" . }}-config
  labels:
    {{- include "templatepg.labels" . | nindent 4 }}
data:
  {{ .Values.config.name  }}: |
                {{- tpl ( toYaml .Values.config.data  ) . | nindent 16 }}
{{- end }}
