{{- if .Values.global.limits }}
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  labels:
    {{- include "apodeixis.labels" . | nindent 4 }}
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi 
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
{{- end }}