{{- if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.fullname" . }}-config
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
  {{ .Values.config.name  }}: |
                {{- tpl ( toYaml .Values.config.data  ) . | nindent 16 }}
{{- end }}